pub(crate) type Boolean = u8;
pub(crate) type BitField = u32;
pub(crate) type Enumerated = u32;
pub(crate) type SInt = i32;
pub(crate) type SizeI = u32;
pub(crate) type SizeIPtr = isize;
// pub(crate) type SShort = i16;
pub(crate) type UInt = u32;
// pub(crate) type UShort = u16;
